version: '3.5'

services:
  discord-bot:
    container_name: discord-bot
    build: .
    command: python src/client.py
    volumes:
      - ./src:/app/bot
    ports:
      - "8000:8000"
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      TEST_MODE: ${TEST_MODE}
    secrets:
      - discord_bot_token

secrets:
  discord_bot_token:
    file: /var/run/secrets/discord_bot_token